### ISSUE TITLE
Release it on npm

### ISSUE THREAD

**Issue by GingerAdonis** [flagmeister/flagmeister.github.io#1]
Great work! It would be great if you could release it on npm, to help us keep our projects up-to-date.

**Comment by Danny-Engelman** [comment]
NPM is on the todo list, once Beta is finished.
I am waiting for an NPM like solution for WebComponents; webcomponents.org is dead and wc.org doesn't get much traction yet

**Comment by Danny-Engelman** [comment]
Decided against NPM, 

I publish all Web Components I create as UNlicensed code, promoting to copy source code.

IMHO developers should create their own BaseClasses, not create more dependencies.
