### ISSUE TITLE
fetch request error

### ISSUE THREAD

**Issue by lyyGov123** [flagmeister/flagmeister.github.io#4]
Fetch requests for resources will cause cross-domain requests, which are intercepted by browsers.
or Fetch config set "{mode:  'no-cors'}"?

![image](http://chuantu.xyz/t6/742/1660787141x2890323465.png)

**Comment by Lin-YingYu** [comment]
[http://chuantu.xyz/t6/742/1660787141x2890323465.png](url)

**Comment by Lin-YingYu** [comment]
![image](http://chuantu.xyz/t6/742/1660787141x2890323465.png)
